# Read the Docs configuration file
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install --upgrade pip
      - pip install -r requirements.txt

python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml

# Optional: environment variables for future integrations
# env:
#   MY_API_KEY: "your-key-here"

# Optional: enable build caching for faster rebuilds
# build:
#   image: latest
#   jobs:
#     post_build:
#       - echo "Build complete"

# Optional: enable versioning if you add mike or similar tools
# versions:
#   only:
#     - latest
#     - stable